name: Run tests and publish report
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
        - name: Checkout gh-pages
          uses: actions/checkout@v3
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages # branch name
            path: gh-pages # checkout path
      
        - name: Allure Report Action
          uses: mgrybyk/allure-report-branch-action@v1
          if: always()
          continue-on-error: true
          id: allure # used in comment to PR
          with:
            report_id: 'self-test'
            gh_pages: 'gh-pages'
            report_dir: './e2e/allure-results'
      
        - name: Git Commit and Push Action
          uses: mgrybyk/git-commit-pull-push-action@v1
          if: always()
          with:
            repository: gh-pages
            branch: gh-pages
            pull_args: --rebase -X ours

            # After publishing to gh-pages
        - name: Comment PR with Allure Report link
          if: ${{ always() && github.event_name == 'pull_request' && steps.allure.outputs.report_url }}
          continue-on-error: true
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              ${{ steps.allure.outputs.test_result_icon }} [Allure Report](${{ steps.allure.outputs.report_url }}) | [History](${{ steps.allure.outputs.report_history_url }})
            comment_tag: allure_report
            mode: recreate
            
