name: Run tests with workflow_call

on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package to test"
        required: true
        type: choice
        options:
          - qpay-customer-ui
          - qpay-ui
      environment:
        description: "Environment to run the tests"
        required: true
        type: choice
        options:
          - int
          - stg
        default: "int"

  # schedule:
  #   - cron: 46 8 * * *
  #   - cron: 47 8 * * *

# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: false

jobs:
  test:
    name: "Run E2E tests"
    uses: ./.github/workflows/mochawesome.yaml
    secrets: inherit
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     instance:
    #       - package-name: qpay-ui
    #         environment: int
    #       - package-name: qpay-customer-ui
    #         environment: int
    #       - package-name: qpay-ui
    #         environment: stg
    #       - package-name: qpay-customer-ui
    #         environment: stg
    with:
      # package-name: ${{ matrix.instance.package-name }}
      environment: ${{ inputs.environment }}
      package-name: >-
        ${{ inputs.package
          || (github.event.schedule == '46 8 * * *' && 'qpay-ui')
          || (github.event.schedule == '47 8 * * *' && 'qpay-customer-ui') 
        }}
