name: Run tests with workflow_call

on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package to test"
        required: true
        type: choice
        options:
          - qpay-customer-ui
          - qpay-ui

  schedule:
    - cron: 0 15 * * *
    - cron: 5 15 * * *

jobs:
  test:
    name: "Run E2E tests"
    uses: ./.github/workflows/mochawesome.yaml
    with:
      package-name: |
        ${{ inputs.package 
            || (github.event.schedule == '0 15 * * *' && 'qpay-ui') 
            || (github.event.schedule == '5 15 * * *' && 'qpay-customer-ui') }}
