name: Run tests with workflow_call

on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package to test"
        required: true
        type: choice
        options:
          - qpay-customer-ui
          - qpay-ui

  schedule:
    - cron: 5 7 * * *
    - cron: 10 7 * * *

jobs:
  test:
    name: "Run E2E tests"
    uses: ./.github/workflows/mochawesome.yaml
    secrets: inherit
    with:
      package-name: |
        ${{ inputs.package || (github.event.schedule == '5 7 * * *' && 'qpay-ui')
            || (github.event.schedule == '10 7 * * *' && 'qpay-customer-ui') }}
