name: Run tests with workflow_call

on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package to test"
        required: true
        type: choice
        options:
          - qpay-customer-ui
          - qpay-ui
      environment:
        description: "Environment to run the tests"
        required: true
        type: choice
        options:
          - int
          - stg
        default: "int"

  schedule:
    - cron: 35 9 * * *
    - cron: 40 9 * * *

jobs:
  test:
    name: "Run E2E tests"
    uses: ./.github/workflows/mochawesome.yaml
    secrets: inherit
    strategy:
      matrix:
        package-name: ['qpay-ui', 'qpay-ui', 'qpay-customer-ui', 'qpay-customer-ui']
        environment: ['int', 'stg', 'int', 'stg']
    with:
      package-name: ${{ matrix.package-name }}
      environment: ${{ matrix.environment }}
      # package-name: >-
      #   ${{ inputs.package
      #     || (github.event.schedule == '35 9 * * *' && 'qpay-ui')
      #     || (github.event.schedule == '40 9 * * *' && 'qpay-customer-ui') 
      #   }}
