name: Run tests with workflow_call

on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package to test"
        required: true
        type: choice
        options:
          - qpay-customer-ui
          - qpay-ui
      environment:
        description: "Environment to run the tests"
        required: true
        type: choice
        options:
          - int
          - stg
        default: "int"

  schedule:
    - cron: 35 9 * * *
    - cron: 40 9 * * *

jobs:
  test:
    name: "Run E2E tests"
    uses: ./.github/workflows/mochawesome.yaml
    secrets: inherit
    concurrency:
      group: e2e-tests
      cancel-in-progress: false
    strategy:
      matrix:
        instance:
          - package-name: qpay-ui
            environment: int
          - package-name: qpay-customer-ui
            environment: int
          - package-name: qpay-ui
            environment: stg
          - package-name: qpay-customer-ui
            environment: stg
    with:
      package-name: ${{ matrix.instance.package-name }}
      environment: ${{ matrix.instance.environment }}
      # package-name: >-
      #   ${{ inputs.package
      #     || (github.event.schedule == '35 9 * * *' && 'qpay-ui')
      #     || (github.event.schedule == '40 9 * * *' && 'qpay-customer-ui') 
      #   }}
